apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla
  labels:
    app: scylla
spec:
  selector:
    matchLabels:
      app: scylla
  template:
    metadata:
      labels:
        app: scylla
    spec:
      containers:
        - name: scylla
          image: scylladb/scylla:latest
          ports:
            - containerPort: 9042
            - containerPort: 9142
            - containerPort: 7000
            - containerPort: 7001
            - containerPort: 10000
            - containerPort: 9180
            - containerPort: 9100
            - containerPort: 9160
            - containerPort: 19042
            - containerPort: 19142
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
          args:
            - "--smp 1"

---

apiVersion: v1
kind: Service
metadata:
  name: scylla
spec:
  selector:
    app: scylla
  ports:
    - port: 9042
      targetPort: 9042
      name: a
    - port: 9142
      targetPort: 9142
      name: aa
    - port: 7000
      name: b
      targetPort: 7000
    - port: 7001
      name: c
      targetPort: 7001
    - port: 7199
      name: d
      targetPort: 7199
    - port: 10000
      targetPort: 10000
      name: e
    - port: 9180
      targetPort: 9180
      name: f
    - port: 9100
      targetPort: 9100
      name: g
    - port: 9160
      targetPort: 9160
      name: h
    - port: 19042
      targetPort: 19042
      name: i
    - port: 19142
      targetPort: 19142
      name: j

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: scheduler:latest
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "100Mi"
            cpu: "1"
        env:
        - name: ENV_TYPE
          value: Development

---

apiVersion: v1
kind: Service
metadata:
  name: scheduler
spec:
  selector:
    app: scheduler
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
  type: NodePort
